version: '3.8'

services:
  smauto:
    image: goaldsl
    command: uvicorn goal_dsl.api:api --host 0.0.0.0 --port 8080 --root-path /goaldsl
    ports:
      - 8082:8080
    environment:
      - API_KEY=
