version: '3.8'

services:
  goaldsl:
    image: goaldsl
    command: uvicorn goal_dsl.api:api --host 0.0.0.0 --port 8080 --root-path ${ROOT_PATH:-/}
    ports:
      - ${PORT:-8082}:8080
    environment:
      - API_KEY=${API_KEY}
