version: '3.8'

services:
  goaldsl:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    command: uvicorn goal_dsl.api:api --host 0.0.0.0 --port 8080 --root-path ${ROOT_PATH:-/} --workers ${WORKERS:-1}
    ports:
      - ${PORT:-8082}:8080
