@startuml
set namespaceSeparator .


class goal_dsl.Model  {
}


class goal_dsl.Goal <<abstract>> {
}


class goal_dsl.AreaGoal <<abstract>> {
}


class goal_dsl.PoseGoal  {
  name : ID
  maxDeviation : FLOAT
  listeningTopic : STRING
}


class goal_dsl.TopicGoal <<abstract>> {
}


class goal_dsl.TrajectoryGoal <<abstract>> {
}


class goal_dsl.ComplexGoal  {
  name : ID
  algorithm : ComplexGoalAlgorithmType
}


class goal_dsl.TopicMessageReceivedGoal  {
  name : ID
  param : STRING
}


class goal_dsl.TopicMessageParamGoal  {
  name : ID
  param : list[STRING]
  expression : STRING
}


class goal_dsl.RectangleAreaGoal  {
  name : ID
  sideLength : FLOAT
  listeningTopic : STRING
}


class goal_dsl.CircularAreaGoal  {
  name : ID
  radius : FLOAT
  listeningTopic : STRING
}


class goal_dsl.StraightLineAreaGoal  {
  name : ID
  listeningTopic : STRING
}


class goal_dsl.StraightLineTrajectoryGoal  {
  name : ID
  maxDeviation : FLOAT
  listeningTopic : STRING
}


class goal_dsl.CustomPointsTrajectoryGoal  {
  name : ID
  maxDeviation : FLOAT
  listeningTopic : STRING
}


class goal_dsl.OrientationGoal  {
  name : ID
  maxDeviation : FLOAT
  listeningTopic : STRING
}


class goal_dsl.PointGoal  {
  name : ID
  maxDeviation : FLOAT
  listeningTopic : STRING
}


class goal_dsl.Point <<abstract>> {
}


class goal_dsl.Orientation <<abstract>> {
}


class goal_dsl.Point2D  {
  xAxis : FLOAT
  yAxis : FLOAT
}


class goal_dsl.Point3D  {
  xAxis : FLOAT
  yAxis : FLOAT
  zAxis : FLOAT
}


class goal_dsl.Orientation2D  {
  xAxis : FLOAT
  yAxis : FLOAT
}


class goal_dsl.Orientation3D  {
  xAxis : FLOAT
  yAxis : FLOAT
  zAxis : FLOAT
}


class goal_dsl.TimeConstraint  {
  name : ID
  type : TimingConstraintType
  minDuration : FLOAT
  maxDuration : FLOAT
}


class goal_dsl.Import  {
  importURI : FQN
  name : ID
}


goal_dsl.Model *-- "0..*" goal_dsl.Import
goal_dsl.Model *-- "0..*" goal_dsl.Goal
goal_dsl.Model *-- "0..*" goal_dsl.TimeConstraint
goal_dsl.Goal <|-- goal_dsl.TopicGoal
goal_dsl.Goal <|-- goal_dsl.AreaGoal
goal_dsl.Goal <|-- goal_dsl.PoseGoal
goal_dsl.Goal <|-- goal_dsl.TrajectoryGoal
goal_dsl.Goal <|-- goal_dsl.ComplexGoal
goal_dsl.AreaGoal <|-- goal_dsl.RectangleAreaGoal
goal_dsl.AreaGoal <|-- goal_dsl.CircularAreaGoal
goal_dsl.AreaGoal <|-- goal_dsl.StraightLineAreaGoal
goal_dsl.PoseGoal *-- goal_dsl.Orientation
goal_dsl.PoseGoal *-- goal_dsl.Point
goal_dsl.PoseGoal o-- goal_dsl.TimeConstraint
goal_dsl.TopicGoal <|-- goal_dsl.TopicMessageReceivedGoal
goal_dsl.TopicGoal <|-- goal_dsl.TopicMessageParamGoal
goal_dsl.TrajectoryGoal <|-- goal_dsl.StraightLineTrajectoryGoal
goal_dsl.TrajectoryGoal <|-- goal_dsl.CustomPointsTrajectoryGoal
goal_dsl.ComplexGoal o-- goal_dsl.TimeConstraint
goal_dsl.ComplexGoal o-- "1..*" goal_dsl.Goal
goal_dsl.TopicMessageReceivedGoal o-- goal_dsl.TimeConstraint
goal_dsl.TopicMessageParamGoal o-- goal_dsl.TimeConstraint
goal_dsl.RectangleAreaGoal *-- goal_dsl.Point
goal_dsl.RectangleAreaGoal o-- goal_dsl.TimeConstraint
goal_dsl.CircularAreaGoal *-- goal_dsl.Point
goal_dsl.CircularAreaGoal o-- goal_dsl.TimeConstraint
goal_dsl.StraightLineAreaGoal *-- goal_dsl.Point
goal_dsl.StraightLineAreaGoal *-- goal_dsl.Point
goal_dsl.StraightLineAreaGoal o-- goal_dsl.TimeConstraint
goal_dsl.StraightLineTrajectoryGoal *-- goal_dsl.Point
goal_dsl.StraightLineTrajectoryGoal *-- goal_dsl.Point
goal_dsl.StraightLineTrajectoryGoal o-- goal_dsl.TimeConstraint
goal_dsl.CustomPointsTrajectoryGoal *-- goal_dsl.Point
goal_dsl.CustomPointsTrajectoryGoal *-- goal_dsl.Point
goal_dsl.CustomPointsTrajectoryGoal *-- "1..*" goal_dsl.Point
goal_dsl.CustomPointsTrajectoryGoal o-- goal_dsl.TimeConstraint
goal_dsl.OrientationGoal *-- goal_dsl.Orientation
goal_dsl.OrientationGoal o-- goal_dsl.TimeConstraint
goal_dsl.PointGoal *-- goal_dsl.Point
goal_dsl.PointGoal o-- goal_dsl.TimeConstraint
goal_dsl.Point <|-- goal_dsl.Point2D
goal_dsl.Point <|-- goal_dsl.Point3D
goal_dsl.Orientation <|-- goal_dsl.Orientation2D
goal_dsl.Orientation <|-- goal_dsl.Orientation3D

legend
  Match rules:
  |= Name  |= Rule details |
  | ComplexGoalAlgorithmType | ALL_ACCOMPLISHED\|NONE_ACCOMPLISHED\|AT_LEAST_ONE\|EXACTLY_X_ACCOMPLISHED |
  | FQN | ID (. ID)* |
  | Comment |  |
  | AreaGoalType | AVOID\|REACH |
  | TimingConstraintType | FROM_APP_START\|WITHIN_PERIOD_FROM_APP_START\|FROM_OTHER_GOAL_COMPLETION\|WITHIN_PERIOD_FROM_OTHER_GOAL_COMPLETION\|FROM_GOAL_START |
  | ParamValueConstraintType | EXACT_VALUE\|WITHIN_RANGE\|OUT_OF_RANGE\|EXISTS_IN_COLLECTION |
  | CommentBlock | \\/\\*(.\|\\n)*\?\\*\\/ |
  | CommentLine | \\/\\/.*\?$ |
end legend

@enduml
